name: "Contribution Stats"
description: "Comments on pull requests with monthly lines of code stats for a specified user, aimed for tracking AI agent contributions."
author: "Umut Karakulak"
branding:
  icon: "pie-chart"
  color: "orange"

inputs:
  contributor-name:
    description: "GitHub username to analyze contributions for. Defaults to the pull request author if not provided."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Important to fetch full history

    - name: Calculate Contribution (by Lines of Code)
      id: contribution_stats
      shell: bash
      env:
        CONTRIBUTOR_NAME: ${{ inputs.contributor-name || github.event.pull_request.user.login }}
      run: |
        CONTRIBUTOR_NAME="${CONTRIBUTOR_NAME}"
        MONTH=$(date +%Y-%m)

        # Calculate total lines added and removed for the month
        TOTAL_LINES_CHANGED=$(git log --since="${MONTH}-01" --until="$(date +%Y-%m-%d -d '+1 month')" --numstat --pretty=format:'' | awk '{ added += $1; removed += $2 } END { print "Added:" added ",Removed:" removed }')
        TOTAL_ADDED_LINES=$(echo "$TOTAL_LINES_CHANGED" | awk -F'[:,]' '{print $2}')
        TOTAL_REMOVED_LINES=$(echo "$TOTAL_LINES_CHANGED" | awk -F'[:,]' '{print $4}')


        # Calculate contributor's lines added and removed for the month
        CONTRIBUTOR_LINES_CHANGED=$(git log --author="${CONTRIBUTOR_NAME}" --since="${MONTH}-01" --until="$(date +%Y-%m-%d -d '+1 month')" --numstat --pretty=format:'' | awk '{ added += $1; removed += $2 } END { print "Added:" added ",Removed:" removed }')
        CONTRIBUTOR_ADDED_LINES=$(echo "$CONTRIBUTOR_LINES_CHANGED" | awk -F'[:,]' '{print $2}')
        CONTRIBUTOR_REMOVED_LINES=$(echo "$CONTRIBUTOR_LINES_CHANGED" | awk -F'[:,]' '{print $4}')


        if [[ "$TOTAL_ADDED_LINES" -eq 0 ]]; then
          PERCENTAGE_LINES=0
        else
          PERCENTAGE_LINES=$(echo "scale=2; ($CONTRIBUTOR_ADDED_LINES * 100) / $TOTAL_ADDED_LINES" | bc)
        fi

        echo "contributor_name=$CONTRIBUTOR_NAME" >> "$GITHUB_OUTPUT"
        echo "total_added_lines=$TOTAL_ADDED_LINES" >> "$GITHUB_OUTPUT"
        echo "total_removed_lines=$TOTAL_REMOVED_LINES" >> "$GITHUB_OUTPUT"
        echo "contributor_added_lines=$CONTRIBUTOR_ADDED_LINES" >> "$GITHUB_OUTPUT"
        echo "contributor_removed_lines=$CONTRIBUTOR_REMOVED_LINES" >> "$GITHUB_OUTPUT"
        echo "contribution_percentage_lines=$PERCENTAGE_LINES" >> "$GITHUB_OUTPUT"

    - name: Comment on PR
      uses: actions/github-script@v7
      env:
        CONTRIBUTOR_NAME: ${{ steps.contribution_stats.outputs.contributor_name }}
        TOTAL_ADDED_LINES: ${{ steps.contribution_stats.outputs.total_added_lines }}
        TOTAL_REMOVED_LINES: ${{ steps.contribution_stats.outputs.total_removed_lines }}
        CONTRIBUTOR_ADDED_LINES: ${{ steps.contribution_stats.outputs.contributor_added_lines }}
        CONTRIBUTOR_REMOVED_LINES: ${{ steps.contribution_stats.outputs.contributor_removed_lines }}
        CONTRIBUTION_PERCENTAGE_LINES: ${{ steps.contribution_stats.outputs.contribution_percentage_lines }}
      with:
        script: |
          const issue_url = context.payload.pull_request.html_url;
          const issue_number = context.payload.pull_request.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const contributor_name = process.env.CONTRIBUTOR_NAME;
          const total_added_lines = parseInt(process.env.TOTAL_ADDED_LINES) || 0;
          const total_removed_lines = parseInt(process.env.TOTAL_REMOVED_LINES) || 0;
          const contributor_added_lines = parseInt(process.env.CONTRIBUTOR_ADDED_LINES) || 0;
          const contributor_removed_lines = parseInt(process.env.CONTRIBUTOR_REMOVED_LINES) || 0;
          const contribution_percentage_lines = parseFloat(process.env.CONTRIBUTION_PERCENTAGE_LINES) || 0;
          const month = new Date().toLocaleString('default', { month: 'long', year: 'numeric' });

          const body = `**Contribution Stats for ${contributor_name} in ${month} (Lines of Code):**

          | Metric | Value |
          | ------ | ----- |
          | Total Lines of Code Added this month | ${total_added_lines} |
          | Total Lines of Code Removed this month | ${total_removed_lines} |
          | ${contributor_name} Lines of Code Added this month | ${contributor_added_lines} |
          | ${contributor_name} Lines of Code Removed this month | ${contributor_removed_lines} |
          | ${contributor_name} Contribution Percentage (Lines Added) | ${contribution_percentage_lines}% |

          \`\`\`mermaid
          pie
            title Contribution
            "${contributor_name}" : ${contribution_percentage_lines}
            "Others" : ${100 - contribution_percentage_lines}
          \`\`\`

          *These statistics are for the current month of (${month}).*`;

          return github.rest.issues.createComment({
            issue_number: issue_number,
            owner: owner,
            repo: repo,
            body: body
          });
